# Generated by Django 5.2.10 on 2026-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegenerationjob',
            name='kind',
            field=models.CharField(choices=[('outline', 'Course outline (subjects, chapters, topics)'), ('content', 'Topic material (notes, quiz, assignments, coding)'), ('meta', 'Course description & marketing copy')], default='outline', max_length=20),
        ),
    ]
