"""
Official NTA JEE Main syllabus structure: Subject -> Chapter -> Topics.
Authored notes content for each topic is built by build_notes()/build_formula().
"""

SUBJECTS = {
    'Physics': {
        'code': 'physics', 'color': '#3B82F6', 'icon': 'atom', 'weightage': 33.3,
        'chapters': [
            ('Units and Measurements', ['Units of measurement, SI units', 'Dimensions of physical quantities', 'Dimensional analysis and its applications', 'Errors in measurement']),
            ('Kinematics', ['Frame of reference, motion in a straight line', 'Speed and velocity', 'Uniform and non-uniform motion', 'Scalars and vectors', 'Relative velocity', 'Projectile motion']),
            ('Laws of Motion', ["Newton's laws of motion", 'Momentum and impulse', 'Friction', 'Circular motion, centripetal force']),
            ('Work, Energy and Power', ['Work done by a force', 'Kinetic and potential energy', 'Work-energy theorem, power', 'Collisions']),
            ('Rotational Motion', ['Centre of mass', 'Moment of inertia', 'Torque and angular momentum', 'Rolling motion']),
            ('Gravitation', ["Universal law of gravitation", 'Gravitational potential energy', "Kepler's laws", 'Satellites and escape velocity']),
            ('Properties of Solids and Liquids', ['Elasticity, Hooke\'s law', 'Pressure and Pascal\'s law', "Bernoulli's principle", 'Viscosity and surface tension', 'Thermal expansion, calorimetry']),
            ('Thermodynamics', ['Thermal equilibrium and zeroth law', 'First law of thermodynamics', 'Second law and Carnot engine']),
            ('Kinetic Theory of Gases', ['Equation of state, ideal gas', 'Kinetic theory and pressure', 'Degrees of freedom, specific heats']),
            ('Oscillations and Waves', ['Simple harmonic motion', 'Wave motion and superposition', 'Standing waves and beats', 'Doppler effect']),
            ('Electrostatics', ['Electric charge and field', 'Gauss law', 'Electric potential', 'Capacitance and dielectrics']),
            ('Current Electricity', ["Ohm's law, resistance", "Kirchhoff's laws", 'Wheatstone bridge, potentiometer']),
            ('Magnetic Effects of Current and Magnetism', ['Biot-Savart and Ampere law', 'Force on current and moving charge', 'Magnetic dipole, earth magnetism']),
            ('Electromagnetic Induction and AC', ["Faraday's law, Lenz law", 'Self and mutual inductance', 'Alternating current, LCR circuits']),
            ('Electromagnetic Waves', ['Displacement current', 'EM spectrum and properties']),
            ('Optics', ['Reflection and refraction', 'Lenses and mirrors', "Wave optics: interference, diffraction"]),
            ('Dual Nature of Matter and Radiation', ['Photoelectric effect', 'de Broglie wavelength']),
            ('Atoms and Nuclei', ['Bohr model of atom', 'Radioactivity, mass-energy', 'Nuclear fission and fusion']),
            ('Electronic Devices', ['Semiconductors, p-n junction', 'Diodes and transistors, logic gates']),
            ('Experimental Skills', ['Vernier calipers and screw gauge', 'Meter bridge, ohmmeter']),
        ],
    },
    'Chemistry': {
        'code': 'chemistry', 'color': '#10B981', 'icon': 'flask-conical', 'weightage': 33.3,
        'chapters': [
            ('Some Basic Concepts in Chemistry', ['Mole concept and molar mass', 'Stoichiometry', 'Empirical and molecular formula']),
            ('Atomic Structure', ['Bohr model and spectra', 'Quantum numbers and orbitals', 'Aufbau, Pauli, Hund rules']),
            ('Chemical Bonding and Molecular Structure', ['Ionic and covalent bonding', 'VSEPR theory', 'Hybridisation', 'Molecular orbital theory']),
            ('Chemical Thermodynamics', ['Enthalpy and Hess law', 'Entropy and Gibbs energy', 'Spontaneity']),
            ('Solutions', ['Concentration terms', 'Raoult\'s law', 'Colligative properties']),
            ('Equilibrium', ['Chemical equilibrium, Kc Kp', 'Acids bases and pH', 'Buffer and solubility product']),
            ('Redox Reactions and Electrochemistry', ['Oxidation number, balancing', 'Electrochemical cells, EMF', 'Conductance and electrolysis']),
            ('Chemical Kinetics', ['Rate of reaction', 'Order and molecularity', 'Arrhenius equation']),
            ('Classification and Periodicity', ['Modern periodic law', 'Periodic trends']),
            ('p-Block Elements', ['Group 13-14 trends', 'Group 15-18 elements']),
            ('d- and f-Block Elements', ['Transition elements properties', 'Lanthanoids and actinoids']),
            ('Coordination Compounds', ['Werner theory, nomenclature', 'Isomerism and bonding theories']),
            ('Purification and Characterisation of Organic Compounds', ['Purification techniques', 'Qualitative and quantitative analysis']),
            ('Basic Principles of Organic Chemistry', ['IUPAC nomenclature', 'Electronic effects and isomerism', 'Reaction intermediates']),
            ('Hydrocarbons', ['Alkanes, alkenes, alkynes', 'Aromatic hydrocarbons']),
            ('Haloalkanes and Haloarenes', ['Nature of C-X bond', 'Substitution and elimination']),
            ('Alcohols, Phenols and Ethers', ['Preparation and properties', 'Phenol reactions']),
            ('Aldehydes, Ketones and Carboxylic Acids', ['Carbonyl chemistry', 'Acidity and reactions']),
            ('Amines', ['Classification and basicity', 'Diazonium salts']),
            ('Biomolecules', ['Carbohydrates and proteins', 'Vitamins and nucleic acids']),
            ('Principles of Practical Chemistry', ['Salt analysis', 'Titrations']),
        ],
    },
    'Mathematics': {
        'code': 'mathematics', 'color': '#8B5CF6', 'icon': 'calculator', 'weightage': 33.4,
        'chapters': [
            ('Sets, Relations and Functions', ['Sets and operations', 'Relations and functions', 'Types of functions']),
            ('Complex Numbers and Quadratic Equations', ['Algebra of complex numbers', 'Modulus and argument', 'Quadratic equations and roots']),
            ('Matrices and Determinants', ['Matrix algebra', 'Determinants and properties', 'Inverse and system of equations']),
            ('Permutations and Combinations', ['Fundamental principle of counting', 'Permutations and combinations']),
            ('Binomial Theorem', ['Binomial theorem for positive index', 'General and middle terms']),
            ('Sequences and Series', ['Arithmetic progression', 'Geometric progression', 'Special series']),
            ('Limits, Continuity and Differentiability', ['Limits', 'Continuity', 'Differentiation']),
            ('Integral Calculus', ['Indefinite integrals', 'Definite integrals', 'Area under curves']),
            ('Differential Equations', ['Order and degree', 'Variable separable and linear']),
            ('Coordinate Geometry', ['Straight lines', 'Circles', 'Conic sections']),
            ('Three Dimensional Geometry', ['Direction cosines', 'Line and plane in space']),
            ('Vector Algebra', ['Vectors and operations', 'Scalar and vector products']),
            ('Statistics and Probability', ['Measures of dispersion', 'Probability', 'Bayes theorem']),
            ('Trigonometry', ['Trigonometric ratios and identities', 'Trigonometric equations', 'Inverse trigonometric functions']),
        ],
    },
}
