# Generated by Django 5.2.10 on 2026-08-02 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_notification_email'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('enrollment_request', 'New enrollment request (to admins)'), ('enrollment_approved', 'Enrollment approved (to student)'), ('enrollment_rejected', 'Enrollment declined (to student)')], max_length=40)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['type'],
                'unique_together': {('tenant', 'type')},
            },
        ),
    ]
