# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.studyplan'),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.topic'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['topic', 'content_type'], name='content_con_topic_i_c40523_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['subject', 'status'], name='content_con_subject_fc79ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('student', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('student', 'exam', 'date')},
        ),
    ]
