# Generated by Django 5.2.10 on 2026-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('interactive', 'Interactive'), ('revision', 'Revision Notes'), ('formula', 'Formula Sheet')], max_length=20),
        ),
    ]
