# Generated by Django 5.2.15 on 2026-06-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('video', 'Video'), ('pdf', 'PDF'), ('interactive', 'Interactive'), ('revision', 'Revision Notes'), ('formula', 'Formula Sheet')], max_length=20),
        ),
    ]
