# Generated by Django 5.2.10 on 2026-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_exam_to_course'),
        ('exams', '0007_rename_exam_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='courses',
            field=models.ManyToManyField(related_name='contents', to='exams.course'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='exams.course'),
        ),
    ]
