# Generated by Django 5.2.10 on 2026-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_content_courses_alter_studyplan_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='content_videos/'),
        ),
    ]
