# Generated by Django 5.2.10 on 2026-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='material_kind',
            field=models.CharField(choices=[('study', 'Study material'), ('practice', 'Practice questions')], default='study', max_length=20),
        ),
    ]
