# Generated by Django 5.2.10 on 2026-02-02 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('study_time_minutes', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('notes_read', models.PositiveIntegerField(default=0)),
                ('videos_watched', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('mock_tests_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('daily_goal_met', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak_start', models.DateField(blank=True, null=True)),
                ('longest_streak_end', models.DateField(blank=True, null=True)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('topics_attempted', models.PositiveIntegerField(default=0)),
                ('topics_mastered', models.PositiveIntegerField(default=0)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_study_minutes', models.PositiveIntegerField(default=0)),
                ('average_speed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subject Performance',
                'verbose_name_plural': 'Subject Performances',
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery_level', models.PositiveIntegerField(choices=[(1, 'Beginner'), (2, 'Developing'), (3, 'Proficient'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_time_per_question', models.PositiveIntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('streak_correct', models.PositiveIntegerField(default=0)),
                ('needs_revision', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Topic Mastery',
                'verbose_name_plural': 'Topic Masteries',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_study_minutes', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('goals_met', models.PositiveIntegerField(default=0)),
                ('topics_covered', models.PositiveIntegerField(default=0)),
                ('topics_improved', models.PositiveIntegerField(default=0)),
                ('weak_topics', models.JSONField(default=list)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('rank_change', models.IntegerField(default=0)),
                ('vs_last_week', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-week_start'],
            },
        ),
    ]
