# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='streak',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='streak',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectperformance',
            unique_together={('student', 'subject', 'exam')},
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['student', 'mastery_level'], name='analytics_t_student_8987c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('student', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('student', 'week_start')},
        ),
    ]
