# Generated by Django 5.2.10 on 2026-02-02 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_seconds_today', models.PositiveIntegerField(default=0)),
                ('goal_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('goal_achieved_at', models.DateTimeField(blank=True, null=True)),
                ('goal_xp_awarded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
