# Generated by Django 5.2.10 on 2026-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_exam_to_course'),
        ('exams', '0007_rename_exam_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='exams.course'),
        ),
        migrations.AlterField(
            model_name='subjectperformance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='exams.course'),
        ),
    ]
