# Generated by Django 5.2.10 on 2026-07-25 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_landingpage_legaldocument'),
        ('exams', '0013_course_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('gmeet', 'Google Meet'), ('in_house', 'In-house Live')], default='gmeet', max_length=20)),
                ('meeting_url', models.URLField(blank=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('host_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='exams.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='exams.subject')),
                ('tenant', models.ForeignKey(help_text='Required: no live class without tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='core.tenant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['topic', 'status'], name='liveclass_l_topic_i_ee1021_idx'), models.Index(fields=['course', 'status'], name='liveclass_l_course__6fbceb_idx')],
            },
        ),
    ]
