# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('competitive', 'Competitive Exam'), ('board', 'Board Exam'), ('entrance', 'Entrance Exam'), ('government', 'Government Job Exam')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='exam_icons/')),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marking_ratio', models.DecimalField(decimal_places=2, default=0.25, help_text='e.g., 0.25 means 1/4 negative marking', max_digits=3)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weightage in the exam', max_digits=5)),
                ('total_topics', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('exams', models.ManyToManyField(related_name='subjects', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('estimated_study_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_content', models.PositiveIntegerField(default=0)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='exams.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('book_reference', models.CharField(blank=True, max_length=200)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='exams.subject')),
                ('topics', models.ManyToManyField(related_name='chapters', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='TopicExamRelevance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('average_questions', models.PositiveIntegerField(default=0, help_text='Average questions from this topic in the exam')),
                ('marks_weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.topic')),
            ],
            options={
                'verbose_name': 'Topic Exam Relevance',
                'verbose_name_plural': 'Topic Exam Relevances',
                'unique_together': {('topic', 'exam')},
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='exams',
            field=models.ManyToManyField(related_name='topics', through='exams.TopicExamRelevance', to='exams.exam'),
        ),
    ]
