# Generated by Django 5.2.10 on 2026-03-04 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_chapter_topics_to_through(apps, schema_editor):
    """Copy existing chapter-topic M2M links into ChapterTopic with order before we switch to through."""
    from django.db import connection
    from collections import defaultdict
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT chapter_id, topic_id FROM exams_chapter_topics ORDER BY chapter_id"
            )
            rows = cursor.fetchall()
    except Exception:
        return  # Table may not exist (e.g. fresh DB)
    Chapter = apps.get_model('exams', 'Chapter')
    ChapterTopic = apps.get_model('exams', 'ChapterTopic')
    Topic = apps.get_model('exams', 'Topic')
    by_chapter = defaultdict(list)
    for chapter_id, topic_id in rows:
        by_chapter[chapter_id].append(topic_id)
    for chapter_id, topic_ids in by_chapter.items():
        chapter = Chapter.objects.get(pk=chapter_id)
        for order, topic_id in enumerate(topic_ids):
            topic = Topic.objects.get(pk=topic_id)
            ChapterTopic.objects.create(chapter=chapter, topic=topic, order=order)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0002_chapter_tenant_exam_tenant_subject_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_topics', to='exams.chapter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_topics', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Chapter Topic',
                'verbose_name_plural': 'Chapter Topics',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'topic')},
            },
        ),
        migrations.RunPython(copy_chapter_topics_to_through, noop_reverse),
    ]
