# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_chapter_topic_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='topics',
        ),
        migrations.AddField(
            model_name='chapter',
            name='topics',
            field=models.ManyToManyField(
                blank=True,
                related_name='chapters',
                through='exams.ChapterTopic',
                through_fields=('chapter', 'topic'),
                to='exams.topic',
            ),
        ),
    ]
