# Generated by Django 5.2.10 on 2026-03-06 17:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_subject_exam(apps, schema_editor):
    """Set subject.exam from first linked exam in the M2M before we remove it."""
    Subject = apps.get_model('exams', 'Subject')
    Exam = apps.get_model('exams', 'Exam')
    fallback_exam = Exam.objects.filter(status='active').first()
    for subject in Subject.objects.all():
        first = subject.exams.first()
        subject.exam_id = (first or fallback_exam).id if (first or fallback_exam) else None
        if subject.exam_id:
            subject.save(update_fields=['exam_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_chapter_use_chapter_topic_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam'),
        ),
        migrations.RunPython(backfill_subject_exam, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subject',
            name='exams',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'exam')},
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam'),
        ),
    ]
