# Generated by Django 5.2.10 on 2026-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0007_rename_exam_to_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='topiccourserelevance',
            options={'verbose_name': 'Topic Course Relevance', 'verbose_name_plural': 'Topic Course Relevances'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('competitive', 'Competitive Course'), ('board', 'Board Course'), ('entrance', 'Entrance Course'), ('government', 'Government Job Course')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='course_icons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weightage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage weightage in the course', max_digits=5),
        ),
        migrations.AlterField(
            model_name='topiccourserelevance',
            name='average_questions',
            field=models.PositiveIntegerField(default=0, help_text='Average questions from this topic in the course'),
        ),
    ]
