# Generated by Django 5.2.10 on 2026-07-04 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'instructor'}, related_name='instructing_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
