# Generated by Django 5.2.10 on 2026-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_course_pricing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.CharField(choices=[('classic', 'Classic — navy & gold, ornate border'), ('modern', 'Modern — bold color blocks'), ('elegant', 'Elegant — cream & gold, refined'), ('minimal', 'Minimal — clean & monochrome')], default='classic', max_length=20),
        ),
    ]
