# Generated by Django 5.2.10 on 2026-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_course_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequential_chapter_unlock',
            field=models.BooleanField(default=False, help_text='If enabled, students must finish each chapter before the next one in the same subject unlocks.'),
        ),
    ]
