# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('quiz', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='mock_test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.mocktestattempt'),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.mocktest'),
        ),
        migrations.AddField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(related_name='questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(related_name='mock_tests', through='quiz.MockTestQuestion', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quiz.QuizQuestion', to='quiz.question'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='quiz_questi_topic_i_ad0e50_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'status'], name='quiz_questi_subject_5c66cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mocktestquestion',
            unique_together={('mock_test', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
    ]
