# Generated by Django 5.2.10 on 2026-02-02 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('wrong_answer', 'Wrong Answer/Solution'), ('unclear_question', 'Unclear Question'), ('wrong_options', 'Wrong/Missing Options'), ('formatting_issue', 'Formatting Issue'), ('typo', 'Typo/Spelling Error'), ('wrong_topic', 'Wrong Topic/Subject'), ('duplicate', 'Duplicate Question'), ('outdated', 'Outdated Information'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quiz.question')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to='users.studentprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Report',
                'verbose_name_plural': 'Question Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
