# Generated by Django 5.2.10 on 2026-02-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_question_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestquestion',
            name='marks_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override marks for this question in this mock test (null = use question default)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='negative_marks_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override negative marks for this question in this mock test (null = use question default)', max_digits=5, null=True),
        ),
    ]
