# Generated by Django 5.2.10 on 2026-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_tenant_mocktest_tenant_mocktestattempt_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='is_pyp',
            field=models.BooleanField(default=False, help_text='Is this a Previous Year Paper?'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='pyp_date',
            field=models.DateField(blank=True, help_text='Actual exam date', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='pyp_session',
            field=models.CharField(blank=True, help_text='e.g., January, April', max_length=100),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='pyp_shift',
            field=models.CharField(blank=True, help_text='e.g., Shift 1, Shift 2', max_length=50),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='pyp_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g., 2024', null=True),
        ),
    ]
