# Generated by Django 5.2.10 on 2026-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_course_options_and_more'),
        ('quiz', '0008_rename_exam_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='exams.course'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='pyp_date',
            field=models.DateField(blank=True, help_text='Actual course date', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(related_name='questions', to='exams.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exams.course'),
        ),
    ]
