# Generated by Django 5.2.15 on 2026-07-08 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0010_alter_course_course_type'),
        ('quiz', '0009_alter_mocktest_course_alter_mocktest_pyp_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses whose enrolled students can attempt. Empty = all registered students in the tenant.', related_name='linked_mock_tests', to='exams.course'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='fullscreen_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='result_visibility',
            field=models.CharField(choices=[('immediate', 'Show results on submission'), ('on_release', 'Hide results until released by admin')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='results_released',
            field=models.BooleanField(default=False, help_text='When result_visibility=on_release, results become visible to students once this is True.'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='start_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='grading_status',
            field=models.CharField(choices=[('auto_graded', 'Auto-graded'), ('pending_manual', 'Pending manual grading'), ('graded', 'Fully graded')], default='auto_graded', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='exams.course'),
        ),
        migrations.CreateModel(
            name='MockTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_type', models.CharField(choices=[('mcq', 'Multiple Choice (Single)'), ('mcq_multi', 'Multiple Choice (Multiple)'), ('numerical', 'Numerical'), ('subjective', 'Subjective'), ('coding', 'Coding')], default='mcq', max_length=20)),
                ('section', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField(blank=True)),
                ('question_html', models.TextField(blank=True, help_text='Optional rich-text/HTML statement.')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='mock_items/')),
                ('explanation', models.TextField(blank=True)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('options', models.JSONField(blank=True, default=list)),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('numerical_tolerance', models.DecimalField(decimal_places=5, default=0.01, max_digits=10)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True)),
                ('rubric', models.TextField(blank=True, help_text='Grading guidance shown to admins only.')),
                ('model_answer', models.TextField(blank=True, help_text='Reference answer shown to admins only.')),
                ('allowed_languages', models.JSONField(blank=True, default=list)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('time_limit_ms', models.PositiveIntegerField(default=3000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('coding_test_cases', models.JSONField(blank=True, default=list)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.mocktest')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Mock Test Item',
                'verbose_name_plural': 'Mock Test Items',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('coding_results', models.JSONField(blank=True, default=list)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('needs_manual_grading', models.BooleanField(default=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_answers', to='quiz.mocktestattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_mock_answers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.mocktestitem')),
            ],
            options={
                'verbose_name': 'Mock Test Answer',
                'verbose_name_plural': 'Mock Test Answers',
                'unique_together': {('attempt', 'item')},
            },
        ),
    ]
