# Generated by Django 5.2.10 on 2026-08-02 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_papers/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Text answer'), ('pdf', 'File upload (PDF or ZIP)'), ('either', 'Text or file (PDF or ZIP)')], default='either', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
    ]
