# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='savedresponse',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='chatbot.chatmessage'),
        ),
        migrations.AddField(
            model_name='savedresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_responses', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='savedresponse',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='savedresponse',
            unique_together={('student', 'message')},
        ),
    ]
