# Generated by Django 5.2.10 on 2026-02-02 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILearningStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0)),
                ('average_time_per_question', models.FloatField(default=0)),
                ('current_quiz_streak', models.PositiveIntegerField(default=0)),
                ('longest_quiz_streak', models.PositiveIntegerField(default=0)),
                ('last_quiz_date', models.DateField(blank=True, null=True)),
                ('topic_performance', models.JSONField(default=dict)),
                ('perfect_quizzes', models.PositiveIntegerField(default=0)),
                ('quizzes_above_80', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_learning_stats', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'AI Learning Stats',
                'verbose_name_plural': 'AI Learning Stats',
            },
        ),
        migrations.CreateModel(
            name='AIQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_topic', models.CharField(blank=True, max_length=200)),
                ('quiz_subject', models.CharField(blank=True, max_length=100)),
                ('questions_data', models.JSONField(default=list)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='chatbot.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_attempts', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'AI Quiz Attempt',
                'verbose_name_plural': 'AI Quiz Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_index', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.PositiveIntegerField(default=0)),
                ('user_answer', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chatbot.aiquizattempt')),
            ],
            options={
                'verbose_name': 'AI Quiz Question',
                'verbose_name_plural': 'AI Quiz Questions',
                'ordering': ['attempt', 'question_index'],
            },
        ),
    ]
