# Generated by Django 5.2.10 on 2026-08-06 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_ailearningstats_tenant_aiquizattempt_tenant_and_more'),
        ('core', '0020_tenant_ai_platform_monthly_tokens'),
        ('exams', '0014_course_sequential_chapter_unlock'),
        ('users', '0014_remove_studentprofile_primary_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='exams.course'),
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('student_daily_message_limit', models.PositiveIntegerField(default=50)),
                ('monthly_token_budget', models.PositiveIntegerField(default=0)),
                ('allow_quiz_generation', models.BooleanField(default=True)),
                ('allow_course_context', models.BooleanField(default=True)),
                ('custom_instructions', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('groq', 'Groq (open-source models)'), ('openrouter', 'OpenRouter (free open-source models)'), ('together', 'Together AI (open-source models)'), ('ollama', 'Self-hosted Ollama'), ('custom', 'Custom OpenAI-compatible endpoint')], max_length=32)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('api_version', models.CharField(blank=True, default='2024-10-21', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=2000)),
                ('is_active', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='uniq_tenant_ai_provider')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('tenant', "Tenant's own key"), ('platform', 'Platform key (granted)')], default='tenant', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='chatbot.chatsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'AI Usage Record',
                'verbose_name_plural': 'AI Usage Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='chatbot_aiu_tenant__c5f402_idx'), models.Index(fields=['tenant', 'source', 'created_at'], name='chatbot_aiu_tenant__b510c8_idx')],
            },
        ),
    ]
