# Generated by Django 5.2.10 on 2026-08-07 07:20

from django.db import migrations, models


def drop_generic_topic_labels(apps, schema_editor):
    """Purge meaningless topic labels recorded before per-question tagging.

    Every AI quiz used to be stored as "Practice Quiz", which showed up as a
    strong/weak "topic" and told students nothing. Those entries are removed so
    the insights rebuild from real concepts.
    """
    from chatbot.models import normalize_topic_label

    AIQuizAttempt = apps.get_model('chatbot', 'AIQuizAttempt')
    AILearningStats = apps.get_model('chatbot', 'AILearningStats')

    for attempt in AIQuizAttempt.objects.exclude(quiz_topic='').iterator():
        cleaned = normalize_topic_label(attempt.quiz_topic)
        if cleaned != attempt.quiz_topic:
            attempt.quiz_topic = cleaned
            attempt.save(update_fields=['quiz_topic'])

    for stats in AILearningStats.objects.iterator():
        performance = stats.topic_performance or {}
        cleaned = {}
        changed = False
        for label, data in performance.items():
            new_label = normalize_topic_label(label)
            if not new_label:
                changed = True
                continue
            if new_label != label:
                changed = True
            existing = cleaned.setdefault(
                new_label, {'attempted': 0, 'correct': 0, 'quizzes': 0}
            )
            existing['attempted'] += data.get('attempted', 0)
            existing['correct'] += data.get('correct', 0)
            existing['quizzes'] += data.get('quizzes', 0)
        if changed:
            stats.topic_performance = cleaned
            stats.save(update_fields=['topic_performance'])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatsession_course_aisettings_aiproviderconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizquestion',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(drop_generic_topic_labels, migrations.RunPython.noop),
    ]
