# Generated by Django 5.2.10 on 2026-07-12 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_paymentgateway_webhook_secret_encrypted'),
        ('exams', '0013_course_certificate_enabled_and_more'),
        ('users', '0012_grandfather_existing_users_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], max_length=20)),
                ('provider_order_id', models.CharField(db_index=True, max_length=255)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='exams.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='users.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='users.studentprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_order_id'], name='payments_pa_provide_0e0922_idx'), models.Index(fields=['tenant', 'status'], name='payments_pa_tenant__3562a9_idx')],
            },
        ),
    ]
