# Generated by Django 5.2.10 on 2026-07-25 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('payments', '0003_paymentorder_provider_refund_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='marketing.coupon'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
