# Generated by Django 5.2.10 on 2026-07-10 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_features'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('hackathon', 'Hackathon')], default='job', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'category'], name='jobs_job_tenant__d9154d_idx'),
        ),
    ]
