# Generated by Django 5.2.10 on 2026-07-11 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_features'),
        ('jobs', '0002_job_category_job_jobs_job_tenant__d9154d_idx'),
        ('users', '0012_grandfather_existing_users_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('closed', 'Position closed / filled'), ('expired', 'Link expired or unavailable'), ('other', 'Other')], default='closed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Job Report',
                'verbose_name_plural': 'Job Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='jobs_jobrep_job_id_35aeac_idx')],
                'unique_together': {('job', 'reporter')},
            },
        ),
    ]
