# Generated by Django 5.2.10 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_course_certificate_enabled_and_more'),
        ('jobs', '0003_jobreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='related_jobs', to='exams.course'),
        ),
    ]
