# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('streak', 'Streak Badges'), ('quiz', 'Quiz Badges'), ('mastery', 'Mastery Badges'), ('milestone', 'Milestone Badges'), ('special', 'Special Badges')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('requirements', models.JSONField(default=dict)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('study_time_minutes', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('quiz_complete', 'Quiz Completed'), ('mock_complete', 'Mock Test Completed'), ('daily_goal', 'Daily Goal Met'), ('streak_bonus', 'Streak Bonus'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up Bonus'), ('referral', 'Referral Bonus'), ('challenge_win', 'Challenge Won'), ('manual', 'Manual Adjustment')], max_length=30)),
                ('xp_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('balance_after', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily Challenge'), ('weekly', 'Weekly Challenge'), ('event', 'Special Event'), ('competition', 'Competition')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended')], default='upcoming', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('goal', models.JSONField(default=dict)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('completers', models.PositiveIntegerField(default=0)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='gamification.badge')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_claimed', models.PositiveIntegerField(default=0)),
                ('badge_claimed', models.BooleanField(default=False)),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gamification.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Participation',
                'verbose_name_plural': 'Challenge Participations',
            },
        ),
    ]
