# Generated by Django 5.2.10 on 2026-02-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('gamification', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('student', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['period', 'exam', 'rank'], name='gamificatio_period_6b2d61_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['period_start', 'period_end'], name='gamificatio_period__4f5d40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('student', 'exam', 'period', 'period_start')},
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge')},
        ),
    ]
