# Generated by Django 5.2.10 on 2026-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='transaction_type',
            field=models.CharField(choices=[('quiz_complete', 'Quiz Completed'), ('mock_complete', 'Mock Test Completed'), ('daily_goal', 'Daily Goal Met'), ('streak_bonus', 'Streak Bonus'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up Bonus'), ('referral', 'Referral Bonus'), ('challenge_win', 'Challenge Won'), ('community', 'Community Activity'), ('manual', 'Manual Adjustment')], max_length=30),
        ),
    ]
