# Generated by Django 5.2.15 on 2026-07-04 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0009_course_instructors'),
        ('users', '0010_alter_courseenrollment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=500)),
                ('statement', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('allowed_languages', models.JSONField(blank=True, default=list)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('time_limit_ms', models.PositiveIntegerField(default=3000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='exams.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_problems', to='exams.subject')),
                ('tenant', models.ForeignKey(help_text='Required: no coding problem without tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='core.tenant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Coding Problem',
                'verbose_name_plural': 'Coding Problems',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('stdin', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=1)),
                ('explanation', models.CharField(blank=True, max_length=500)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.codingproblem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('language', models.CharField(choices=[('python', 'Python 3.12'), ('cpp', 'C++ (GCC 10.2)'), ('java', 'Java 15')], max_length=20)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('done', 'Evaluated'), ('error', 'Engine error')], default='done', max_length=20)),
                ('results', models.JSONField(blank=True, default=list)),
                ('compile_output', models.TextField(blank=True)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('passed_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='users.studentprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Coding Submission',
                'verbose_name_plural': 'Coding Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['problem', 'student'], name='coding_codi_problem_7495e0_idx')],
            },
        ),
    ]
