# Generated by Django 5.2.10 on 2026-02-03 12:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0002_add_profile_personal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_best_answer', models.BooleanField(default=False)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='users.studentprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-is_best_answer', '-likes_count', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('questions_count', models.PositiveIntegerField(default=0)),
                ('polls_count', models.PositiveIntegerField(default=0)),
                ('quizzes_count', models.PositiveIntegerField(default=0)),
                ('answers_count', models.PositiveIntegerField(default=0)),
                ('best_answers_count', models.PositiveIntegerField(default=0)),
                ('likes_given', models.PositiveIntegerField(default=0)),
                ('likes_received', models.PositiveIntegerField(default=0)),
                ('total_community_xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_stats', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Community Stats',
                'verbose_name_plural': 'Community Stats',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('question', 'Question'), ('poll', 'Poll'), ('quiz', 'Quiz')], default='question', max_length=20)),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('hidden', 'Hidden')], default='active', max_length=20)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='users.studentprofile')),
                ('best_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_for', to='community.comment')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='exams.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='exams.subject')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_text', models.CharField(max_length=200)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='community.post')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to='users.studentprofile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='CommunityQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='community.post')),
            ],
            options={
                'verbose_name': 'Community Quiz',
                'verbose_name_plural': 'Community Quizzes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_answer', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='community.communityquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_quiz_attempts', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
            },
        ),
        migrations.CreateModel(
            name='CommunityLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('answers_count', models.PositiveIntegerField(default=0)),
                ('best_answers_count', models.PositiveIntegerField(default=0)),
                ('likes_received', models.PositiveIntegerField(default=0)),
                ('community_xp', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_leaderboard', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Community Leaderboard',
                'verbose_name_plural': 'Community Leaderboard',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['period', 'period_start', 'rank'], name='community_c_period_4b5952_idx')],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'unique_together': {('user', 'option')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status', '-created_at'], name='community_p_post_ty_4abd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='community_p_author__c7cd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['exam', '-created_at'], name='community_p_exam_id_4c4a08_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post'), name='unique_post_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_comment_like'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz')},
        ),
    ]
