# Generated by Django 5.2.10 on 2026-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_tenant_communityleaderboard_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/comments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/posts/'),
        ),
    ]
