# Generated by Django 5.2.15 on 2026-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='best_answer_xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
