# Generated by Django 5.2.15 on 2026-07-08 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_courses'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('question', 'Question'), ('poll', 'Poll'), ('quiz', 'Quiz'), ('event', 'Event')], default='question', max_length=20),
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(max_length=500)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='community.post')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Community Event',
                'verbose_name_plural': 'Community Events',
                'indexes': [models.Index(fields=['start_at'], name='community_c_start_a_913499_idx')],
            },
        ),
    ]
