# Generated by Django migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='coaching',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='board',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state', 'State Board'), ('ib', 'IB'), ('igcse', 'IGCSE'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medium',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('bilingual', 'Bilingual'), ('other', 'Other')], default='english', max_length=20),
        ),
    ]
