# Generated by Django 5.2.10 on 2026-02-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_examenrollment_tenant_studentprofile_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant'),
        ),
    ]
