# Generated by Django 5.2.15 on 2026-06-29 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    ExamEnrollment = apps.get_model('users', 'ExamEnrollment')
    ExamEnrollment.objects.filter(is_active=True).update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
