# Generated by Django 5.2.10 on 2026-07-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_exam_to_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'verbose_name': 'Course Enrollment', 'verbose_name_plural': 'Course Enrollments'},
        ),
    ]
