# Generated by Django 5.2.10 on 2026-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
