# Generated by Django 5.2.10 on 2026-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
