# Generated by Django 5.2.10 on 2026-07-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_favicon_tenant_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('sunrise', 'Sunrise Orange'), ('ocean', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('violet', 'Royal Purple'), ('rose', 'Crimson Rose')], default='sunrise', max_length=32),
        ),
    ]
