# Generated by Django 5.2.10 on 2026-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('sunrise', 'Sunrise Orange'), ('ocean', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('violet', 'Royal Purple'), ('rose', 'Crimson Rose'), ('indigo', 'Midnight Indigo'), ('slate', 'Graphite Slate'), ('amber', 'Golden Amber'), ('cherry', 'Cherry Red'), ('lime', 'Fresh Lime')], default='sunrise', max_length=32),
        ),
    ]
