# Generated by Django 5.2.10 on 2026-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tenant_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
    ]
