# Generated by Django 5.2.10 on 2026-07-12 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='request_enrollment_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='request_enrollment_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], max_length=20)),
                ('key_id', models.CharField(blank=True, default='', max_length=255)),
                ('key_secret_encrypted', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
    ]
