# Generated by Django 5.2.10 on 2026-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_request_enrollment_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
