# Generated by Django 5.2.10 on 2026-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paymentgateway_webhook_secret_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree'), ('payu', 'PayU')], max_length=20),
        ),
    ]
