# Generated by Django 5.2.10 on 2026-07-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paymentgateway_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentgateway',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider'), name='uniq_tenant_provider_gateway'),
        ),
    ]
