# Generated by Django 5.2.10 on 2026-07-17 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paymentgateway_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('aurora', 'Aurora — Gradient & Modern'), ('spotlight', 'Spotlight — Bold & Dark'), ('classic', 'Classic — Clean & Light'), ('minimal', 'Minimal — Editorial')], default='aurora', max_length=32)),
                ('is_published', models.BooleanField(default=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('footer', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('refund', 'Refund & Cancellation Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'doc_type'), name='uniq_tenant_legal_doc')],
            },
        ),
    ]
