# Generated by Django 5.2.10 on 2026-07-31 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_landingpage_legaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_locks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspension_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SuperAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=64)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Super Admin Audit Log',
                'verbose_name_plural': 'Super Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_tenant', '-created_at'], name='core_supera_target__0c1864_idx'), models.Index(fields=['-created_at'], name='core_supera_created_4f9a1d_idx')],
            },
        ),
    ]
