# Generated by Django 5.2.10 on 2026-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenant_feature_locks_tenant_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='trialing', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_admins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_courses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='trial', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
