# Generated by Django 5.2.10 on 2026-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_demobooking_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='notification_email',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
