# Generated by Django 5.2.10 on 2026-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_platform_monthly_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
